# Listener MQTT en puerto 1883, accesible desde cualquier IP
listener 1883 0.0.0.0

# Autenticación obligatoria
allow_anonymous false
password_file /mosquitto/config/passwd

# Control de acceso por tópico
acl_file /mosquitto/config/acl

# Persistencia
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true